Algoritmo "par ou impar e positivo ou negativo"
// Autor(a)    : Guilherme Augusto Oliveira de Paula
// Data atual  : 05/03/2020
var
num: inteiro
inicio
escreval("Digite o número")
leia(num)
se (num % 2) = 0 entao
escreval("O número é par")
senao
escreval("O número é impar")
fimse
se (num >= 0) entao
escreval("O número é positivo")
senao
escreval("O número é negativo")
fimse
fimalgoritmo